### ISSUE TITLE
Executables need to be moved to find behaviorNames.json on Windows

### ISSUE THREAD

**Issue by rarmst** [andre-meyer/sm64-randomizer#2]
Dovetailing off #1, a user (who doesn't have a GitHub account to comment here) extracted an executable file into the release subdirectory, where it fails to generate a randomized game with the same error originally reported from the command line version:
[image link](https://cdn.discordapp.com/attachments/280797802815029251/580147203016884225/Capture.PNG)
This is most likely a current working directory issue, solved by moving the .exe files to the sm64-randomizer directory after extraction. It's an easy enough fix, but it might warrant a line in the README on how to get it working.

**Comment by andre-meyer** [comment]
Thank you for checking out the project! I've noticed this error too and I will get out another build very soon to fix this!

**Comment by andre-meyer** [comment]
Please check the newest release! I fixed this issue.
