### ISSUE TITLE
Merge conflict in gui.py committed into repository

### ISSUE THREAD

**Issue by jcarvajal288** [andre-meyer/sm64-randomizer#3]
at line 269 in gui.py there is a merge conflict still present in the code:

    <<<<<<< HEAD
        if 'default' in field and type(field) is dict:
          if 'GUI' in field['default']:
            self.selections

    =======
    >>>>>>> 4b060e46564f7771d95c8c5f8a3fa2f764ac6a08

**Comment by andre-meyer** [comment]
Thanks so much for reporting this issue. I have fixed it on master now. Please let me know if you find similar issues!
