### ISSUE TITLE
module 'plotly' not present in requirements.txt

### ISSUE THREAD

**Issue by jcarvajal288** [andre-meyer/sm64-randomizer#4]
I installed dependencies using `pip3 install -r requirements.txt` but I still needed to install the `plotly` module afterward for the program to run.

**Comment by andre-meyer** [comment]
Thanks so much for reporting this issue. I have fixed it on master now. Please let me know if you find similar issues!

I removed `plotly` as a hard dependency, I only need it to run the application with `DEBUG=PLOT` - this view displays the various level geometries for easier debugging. It is only imported with this `DEBUG` env var.
